name: Deploy to S3

on:
  push:
    branches:
      - main  # Change this if your main branch has a different name

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Use the latest version

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2  # Use the latest version
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2  # Change this to your desired region

      - name: Deploy to S3
        run: |
          aws s3 sync ./path/to/your/site s3://somali-culture